#pragma once

#include "nimconfig.h"

#ifndef CONFIG_BT_BLEGC_SCAN_DURATION_MS
#define CONFIG_BT_BLEGC_SCAN_DURATION_MS 30000
#endif

#ifndef CONFIG_BT_BLEGC_CONN_TIMEOUT_MS
#define CONFIG_BT_BLEGC_CONN_TIMEOUT_MS 15000
#endif

#ifndef CONFIG_BT_BLEGC_MAX_CONNECTIONS
#define CONFIG_BT_BLEGC_MAX_CONNECTIONS CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#endif

#ifndef CONFIG_BT_BLEGC_DEVICE_NAME
#define CONFIG_BT_BLEGC_DEVICE_NAME "ESP32"
#endif

#ifndef CONFIG_BT_BLEGC_POWER_DBM
#define CONFIG_BT_BLEGC_POWER_DBM 3
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_IO_CAP
#define CONFIG_BT_BLEGC_SECURITY_IO_CAP BLE_HS_IO_NO_INPUT_OUTPUT
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_AUTH
#define CONFIG_BT_BLEGC_SECURITY_AUTH BLE_SM_PAIR_AUTHREQ_BOND | BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC
#endif
