#pragma once

#include <nimconfig.h>
#include <cstdio>
#include <Esp.h>

#ifndef CONFIG_BT_BLEGC_WRITER_BUFFER_MAX_CAPACITY
#define CONFIG_BT_BLEGC_WRITER_BUFFER_MAX_CAPACITY 1024
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_DURATION_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_DURATION_MS 60000
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_INTERVAL_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_INTERVAL_MS 10
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_WINDOW_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_WINDOW_MS 10
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_ACTIVE
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_ACTIVE 1
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_DURATION_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_DURATION_MS 240000
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_INTERVAL_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_INTERVAL_MS 1280
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_WINDOW_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_WINDOW_MS 15
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_ACTIVE
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_ACTIVE 0
#endif

#ifndef CONFIG_BT_BLEGC_CONN_TIMEOUT_MS
#define CONFIG_BT_BLEGC_CONN_TIMEOUT_MS 15000
#endif

#ifndef CONFIG_BT_BLEGC_DEVICE_NAME
#define CONFIG_BT_BLEGC_DEVICE_NAME ESP.getChipModel()
#endif

#ifndef CONFIG_BT_BLEGC_POWER_DBM
#define CONFIG_BT_BLEGC_POWER_DBM 0
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_IO_CAP
#define CONFIG_BT_BLEGC_SECURITY_IO_CAP BLE_HS_IO_NO_INPUT_OUTPUT
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_AUTH
#define CONFIG_BT_BLEGC_SECURITY_AUTH BLE_SM_PAIR_AUTHREQ_BOND | BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC
#endif
