#pragma once

#include <cstdio>
#include <nimconfig.h>

#ifndef CONFIG_BT_BLEGC_LOG_LEVEL
#if defined(CORE_DEBUG_LEVEL)
#define CONFIG_BT_BLEGC_LOG_LEVEL CORE_DEBUG_LEVEL
#else
#define CONFIG_BT_BLEGC_LOG_LEVEL 1
#endif
#endif

#ifndef CONFIG_BT_BLEGC_ENABLE_DEBUG_DATA
#define CONFIG_BT_BLEGC_ENABLE_DEBUG_DATA 0
#endif

#ifndef CONFIG_BT_BLEGC_MAX_CONNECTION_SLOTS
#if defined(CONFIG_BT_NIMBLE_MAX_CONNECTIONS)
#define CONFIG_BT_BLEGC_MAX_CONNECTION_SLOTS CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#else
#define CONFIG_BT_BLEGC_MAX_CONNECTION_SLOTS 9
#endif
#endif

#ifndef CONFIG_BT_BLEGC_WRITER_MAX_CAPACITY
#define CONFIG_BT_BLEGC_WRITER_MAX_CAPACITY 1024
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_DURATION_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_DURATION_MS 30000
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_INTERVAL_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_INTERVAL_MS 10
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_WINDOW_MS
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_WINDOW_MS 10
#endif

#ifndef CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_ACTIVE
#define CONFIG_BT_BLEGC_HIGH_DUTY_SCAN_ACTIVE 1
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_DURATION_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_DURATION_MS 60000
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_INTERVAL_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_INTERVAL_MS 1280
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_WINDOW_MS
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_WINDOW_MS 15
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_ACTIVE
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_ACTIVE 0
#endif

#ifndef CONFIG_BT_BLEGC_LOW_DUTY_SCAN_RESTART_LIMIT
#define CONFIG_BT_BLEGC_LOW_DUTY_SCAN_RESTART_LIMIT 10
#endif

#ifndef CONFIG_BT_BLEGC_CONN_TIMEOUT_MS
#define CONFIG_BT_BLEGC_CONN_TIMEOUT_MS 15000
#endif

#ifndef CONFIG_BT_BLEGC_DEVICE_NAME
#define CONFIG_BT_BLEGC_DEVICE_NAME "ESP32"
#endif

#ifndef CONFIG_BT_BLEGC_POWER_DBM
#define CONFIG_BT_BLEGC_POWER_DBM 3
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_IO_CAP
#define CONFIG_BT_BLEGC_SECURITY_IO_CAP BLE_HS_IO_NO_INPUT_OUTPUT
#endif

#ifndef CONFIG_BT_BLEGC_SECURITY_AUTH
#define CONFIG_BT_BLEGC_SECURITY_AUTH BLE_SM_PAIR_AUTHREQ_BOND | BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC
#endif
